var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/visits/[visitId]/owner-summary/route.js")
R.c("server/chunks/[externals]_next_dist_b01ab6e1._.js")
R.c("server/chunks/[root-of-the-server]__55b9e8f9._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_171c1591.js")
R.c("server/chunks/[root-of-the-server]__f408c708._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_ec6621a1._.js")
R.c("server/chunks/node_modules_openai_index_mjs_88cf4560._.js")
R.c("server/chunks/ce889_server_app_api_visits_[visitId]_owner-summary_route_actions_0f40b392.js")
R.m(73161)
module.exports=R.m(73161).exports
