// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../../app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/anatomy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/anatomy">> = Specific
  const handler = {} as typeof import("../../../app/anatomy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/appointments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/appointments">> = Specific
  const handler = {} as typeof import("../../../app/appointments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing">> = Specific
  const handler = {} as typeof import("../../../app/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../../app/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/confirmed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/confirmed">> = Specific
  const handler = {} as typeof import("../../../app/confirmed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/consent/[ownerId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/consent/[ownerId]">> = Specific
  const handler = {} as typeof import("../../../app/consent/[ownerId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/horses/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/horses/[id]">> = Specific
  const handler = {} as typeof import("../../../app/horses/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/horses/[id]/progress/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/horses/[id]/progress">> = Specific
  const handler = {} as typeof import("../../../app/horses/[id]/progress/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/horses/[id]/spine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/horses/[id]/spine">> = Specific
  const handler = {} as typeof import("../../../app/horses/[id]/spine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/intake/[ownerId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/intake/[ownerId]">> = Specific
  const handler = {} as typeof import("../../../app/intake/[ownerId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/intake/view/[formId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/intake/view/[formId]">> = Specific
  const handler = {} as typeof import("../../../app/intake/view/[formId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/landing">> = Specific
  const handler = {} as typeof import("../../../app/landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../../app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/owners/[ownerId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owners/[ownerId]">> = Specific
  const handler = {} as typeof import("../../../app/owners/[ownerId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../../app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/appointments/[appointmentId]/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/appointments/[appointmentId]/confirm">> = Specific
  const handler = {} as typeof import("../../../app/api/appointments/[appointmentId]/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/appointments/[appointmentId]/email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/appointments/[appointmentId]/email">> = Specific
  const handler = {} as typeof import("../../../app/api/appointments/[appointmentId]/email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/billing/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/checkout">> = Specific
  const handler = {} as typeof import("../../../app/api/billing/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/billing/ensure-practitioner/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/ensure-practitioner">> = Specific
  const handler = {} as typeof import("../../../app/api/billing/ensure-practitioner/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/billing/portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/portal">> = Specific
  const handler = {} as typeof import("../../../app/api/billing/portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/billing/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/webhook">> = Specific
  const handler = {} as typeof import("../../../app/api/billing/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/consent/[consentId]/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/consent/[consentId]/pdf">> = Specific
  const handler = {} as typeof import("../../../app/api/consent/[consentId]/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/consent/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/consent/submit">> = Specific
  const handler = {} as typeof import("../../../app/api/consent/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../../app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/generate-soap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate-soap">> = Specific
  const handler = {} as typeof import("../../../app/api/generate-soap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/intake/[formId]/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/intake/[formId]/pdf">> = Specific
  const handler = {} as typeof import("../../../app/api/intake/[formId]/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/intake/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/intake/submit">> = Specific
  const handler = {} as typeof import("../../../app/api/intake/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/onboarding/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding/complete">> = Specific
  const handler = {} as typeof import("../../../app/api/onboarding/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/onboarding/setup-profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding/setup-profile">> = Specific
  const handler = {} as typeof import("../../../app/api/onboarding/setup-profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/owners/[ownerId]/documents/[documentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/owners/[ownerId]/documents/[documentId]">> = Specific
  const handler = {} as typeof import("../../../app/api/owners/[ownerId]/documents/[documentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/owners/[ownerId]/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/owners/[ownerId]/documents">> = Specific
  const handler = {} as typeof import("../../../app/api/owners/[ownerId]/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/owners/[ownerId]/send-consent-sms/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/owners/[ownerId]/send-consent-sms">> = Specific
  const handler = {} as typeof import("../../../app/api/owners/[ownerId]/send-consent-sms/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/owners/[ownerId]/send-consent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/owners/[ownerId]/send-consent">> = Specific
  const handler = {} as typeof import("../../../app/api/owners/[ownerId]/send-consent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/owners/[ownerId]/send-intake-sms/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/owners/[ownerId]/send-intake-sms">> = Specific
  const handler = {} as typeof import("../../../app/api/owners/[ownerId]/send-intake-sms/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/owners/[ownerId]/send-intake/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/owners/[ownerId]/send-intake">> = Specific
  const handler = {} as typeof import("../../../app/api/owners/[ownerId]/send-intake/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/owners/[ownerId]/send-optin-sms/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/owners/[ownerId]/send-optin-sms">> = Specific
  const handler = {} as typeof import("../../../app/api/owners/[ownerId]/send-optin-sms/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/places/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/places">> = Specific
  const handler = {} as typeof import("../../../app/api/places/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/public/consent/[ownerId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/consent/[ownerId]">> = Specific
  const handler = {} as typeof import("../../../app/api/public/consent/[ownerId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/public/owner/[ownerId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/owner/[ownerId]">> = Specific
  const handler = {} as typeof import("../../../app/api/public/owner/[ownerId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/public/practitioner/[practitionerId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/practitioner/[practitionerId]">> = Specific
  const handler = {} as typeof import("../../../app/api/public/practitioner/[practitionerId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reminders/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reminders/send">> = Specific
  const handler = {} as typeof import("../../../app/api/reminders/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sms/incoming/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sms/incoming">> = Specific
  const handler = {} as typeof import("../../../app/api/sms/incoming/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/upload-logo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload-logo">> = Specific
  const handler = {} as typeof import("../../../app/api/upload-logo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/visits/[visitId]/email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/visits/[visitId]/email">> = Specific
  const handler = {} as typeof import("../../../app/api/visits/[visitId]/email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/visits/[visitId]/owner-summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/visits/[visitId]/owner-summary">> = Specific
  const handler = {} as typeof import("../../../app/api/visits/[visitId]/owner-summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/visits/[visitId]/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/visits/[visitId]/pdf">> = Specific
  const handler = {} as typeof import("../../../app/api/visits/[visitId]/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/landing/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/landing">> = Specific
  const handler = {} as typeof import("../../../app/landing/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
