// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/account" | "/anatomy" | "/appointments" | "/billing" | "/calendar" | "/confirmed" | "/consent/[ownerId]" | "/contact" | "/dashboard" | "/horses/[id]" | "/horses/[id]/progress" | "/horses/[id]/spine" | "/intake/[ownerId]" | "/intake/view/[formId]" | "/landing" | "/login" | "/onboarding" | "/owners/[ownerId]" | "/signup"
type AppRouteHandlerRoutes = "/api/appointments/[appointmentId]/confirm" | "/api/appointments/[appointmentId]/email" | "/api/billing/checkout" | "/api/billing/ensure-practitioner" | "/api/billing/portal" | "/api/billing/webhook" | "/api/consent/[consentId]/pdf" | "/api/consent/submit" | "/api/contact" | "/api/generate-soap" | "/api/intake/[formId]/pdf" | "/api/intake/submit" | "/api/onboarding/complete" | "/api/onboarding/setup-profile" | "/api/owners/[ownerId]/documents" | "/api/owners/[ownerId]/documents/[documentId]" | "/api/owners/[ownerId]/send-consent" | "/api/owners/[ownerId]/send-consent-sms" | "/api/owners/[ownerId]/send-intake" | "/api/owners/[ownerId]/send-intake-sms" | "/api/owners/[ownerId]/send-optin-sms" | "/api/places" | "/api/public/consent/[ownerId]" | "/api/public/owner/[ownerId]" | "/api/public/practitioner/[practitionerId]" | "/api/reminders/send" | "/api/sms/incoming" | "/api/upload-logo" | "/api/visits/[visitId]/email" | "/api/visits/[visitId]/owner-summary" | "/api/visits/[visitId]/pdf"
type PageRoutes = never
type LayoutRoutes = "/" | "/landing"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/account": {}
  "/anatomy": {}
  "/api/appointments/[appointmentId]/confirm": { "appointmentId": string; }
  "/api/appointments/[appointmentId]/email": { "appointmentId": string; }
  "/api/billing/checkout": {}
  "/api/billing/ensure-practitioner": {}
  "/api/billing/portal": {}
  "/api/billing/webhook": {}
  "/api/consent/[consentId]/pdf": { "consentId": string; }
  "/api/consent/submit": {}
  "/api/contact": {}
  "/api/generate-soap": {}
  "/api/intake/[formId]/pdf": { "formId": string; }
  "/api/intake/submit": {}
  "/api/onboarding/complete": {}
  "/api/onboarding/setup-profile": {}
  "/api/owners/[ownerId]/documents": { "ownerId": string; }
  "/api/owners/[ownerId]/documents/[documentId]": { "ownerId": string; "documentId": string; }
  "/api/owners/[ownerId]/send-consent": { "ownerId": string; }
  "/api/owners/[ownerId]/send-consent-sms": { "ownerId": string; }
  "/api/owners/[ownerId]/send-intake": { "ownerId": string; }
  "/api/owners/[ownerId]/send-intake-sms": { "ownerId": string; }
  "/api/owners/[ownerId]/send-optin-sms": { "ownerId": string; }
  "/api/places": {}
  "/api/public/consent/[ownerId]": { "ownerId": string; }
  "/api/public/owner/[ownerId]": { "ownerId": string; }
  "/api/public/practitioner/[practitionerId]": { "practitionerId": string; }
  "/api/reminders/send": {}
  "/api/sms/incoming": {}
  "/api/upload-logo": {}
  "/api/visits/[visitId]/email": { "visitId": string; }
  "/api/visits/[visitId]/owner-summary": { "visitId": string; }
  "/api/visits/[visitId]/pdf": { "visitId": string; }
  "/appointments": {}
  "/billing": {}
  "/calendar": {}
  "/confirmed": {}
  "/consent/[ownerId]": { "ownerId": string; }
  "/contact": {}
  "/dashboard": {}
  "/horses/[id]": { "id": string; }
  "/horses/[id]/progress": { "id": string; }
  "/horses/[id]/spine": { "id": string; }
  "/intake/[ownerId]": { "ownerId": string; }
  "/intake/view/[formId]": { "formId": string; }
  "/landing": {}
  "/login": {}
  "/onboarding": {}
  "/owners/[ownerId]": { "ownerId": string; }
  "/signup": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/landing": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
