var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/horses/[id]/progress/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__2fed46a9._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_e2423459._.js")
R.c("server/chunks/ssr/[root-of-the-server]__45111c85._.js")
R.c("server/chunks/ssr/node_modules_722875e3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__4d4728ef._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_horses_[id]_progress_page_actions_532797c1.js")
R.m(23656)
module.exports=R.m(23656).exports
