var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/visits/[visitId]/email/route.js")
R.c("server/chunks/[externals]__5253994e._.js")
R.c("server/chunks/[root-of-the-server]__f408c708._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_a2533494.js")
R.c("server/chunks/node_modules_ec6621a1._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/[root-of-the-server]__55b9e8f9._.js")
R.c("server/chunks/_next-internal_server_app_api_visits_[visitId]_email_route_actions_999131e9.js")
R.m(39114)
module.exports=R.m(39114).exports
