import { NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

export async function GET(
  req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params

  const { data: invoice } = await supabaseAdmin
    .from('patient_invoices')
    .select('*, human_patients(first_name, last_name, email, phone, address)')
    .eq('id', id)
    .single()

  if (!invoice) {
    return NextResponse.json({ error: 'Invoice not found' }, { status: 404 })
  }

  const { data: prac } = await supabaseAdmin
    .from('practitioners')
    .select('full_name, practice_name, email, phone')
    .eq('id', invoice.practitioner_id)
    .single()

  const pdf = await PDFDocument.create()
  const page = pdf.addPage([612, 792])
  const font = await pdf.embedFont(StandardFonts.Helvetica)
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold)

  const dark = rgb(0.1, 0.1, 0.15)
  const gray = rgb(0.4, 0.4, 0.45)
  const gold = rgb(0.79, 0.64, 0.15)

  let y = 740

  // Header
  page.drawText(prac?.practice_name || prac?.full_name || 'Practice', { x: 50, y, font: fontBold, size: 18, color: dark })
  y -= 18
  if (prac?.email) { page.drawText(prac.email, { x: 50, y, font, size: 9, color: gray }); y -= 12 }
  if (prac?.phone) { page.drawText(prac.phone, { x: 50, y, font, size: 9, color: gray }); y -= 12 }

  // Invoice title
  page.drawText('INVOICE', { x: 430, y: 740, font: fontBold, size: 22, color: gold })
  page.drawText(`#${invoice.invoice_number}`, { x: 430, y: 720, font, size: 10, color: gray })
  page.drawText(`Date: ${invoice.date_issued}`, { x: 430, y: 706, font, size: 9, color: gray })
  if (invoice.due_date) page.drawText(`Due: ${invoice.due_date}`, { x: 430, y: 693, font, size: 9, color: gray })

  y -= 20

  // Bill To
  page.drawText('Bill To:', { x: 50, y, font: fontBold, size: 10, color: dark }); y -= 14
  const pt = invoice.human_patients
  if (pt) {
    page.drawText(`${pt.first_name} ${pt.last_name}`, { x: 50, y, font, size: 10, color: dark }); y -= 13
    if (pt.email) { page.drawText(pt.email, { x: 50, y, font, size: 9, color: gray }); y -= 12 }
    if (pt.phone) { page.drawText(pt.phone, { x: 50, y, font, size: 9, color: gray }); y -= 12 }
    if (pt.address) { page.drawText(pt.address, { x: 50, y, font, size: 9, color: gray }); y -= 12 }
  }

  y -= 20

  // Table header
  page.drawRectangle({ x: 50, y: y - 2, width: 512, height: 18, color: rgb(0.93, 0.93, 0.95) })
  page.drawText('Description', { x: 55, y: y + 2, font: fontBold, size: 9, color: dark })
  page.drawText('Qty', { x: 360, y: y + 2, font: fontBold, size: 9, color: dark })
  page.drawText('Rate', { x: 410, y: y + 2, font: fontBold, size: 9, color: dark })
  page.drawText('Amount', { x: 490, y: y + 2, font: fontBold, size: 9, color: dark })
  y -= 20

  // Line items
  const items = invoice.line_items as { description: string; qty: number; rate: number; amount: number }[]
  for (const item of items) {
    page.drawText(item.description.slice(0, 50), { x: 55, y, font, size: 9, color: dark })
    page.drawText(String(item.qty), { x: 365, y, font, size: 9, color: dark })
    page.drawText(`$${item.rate.toFixed(2)}`, { x: 410, y, font, size: 9, color: dark })
    page.drawText(`$${item.amount.toFixed(2)}`, { x: 490, y, font, size: 9, color: dark })
    y -= 16
  }

  // Totals
  y -= 10
  page.drawLine({ start: { x: 380, y: y + 5 }, end: { x: 562, y: y + 5 }, thickness: 0.5, color: gray })
  page.drawText('Subtotal:', { x: 410, y, font, size: 9, color: gray })
  page.drawText(`$${invoice.subtotal.toFixed(2)}`, { x: 490, y, font, size: 9, color: dark })
  y -= 14

  if (invoice.amount_paid > 0) {
    page.drawText('Paid:', { x: 410, y, font, size: 9, color: gray })
    page.drawText(`-$${invoice.amount_paid.toFixed(2)}`, { x: 490, y, font, size: 9, color: rgb(0.2, 0.6, 0.2) })
    y -= 14
  }

  page.drawText('Balance Due:', { x: 410, y, font: fontBold, size: 11, color: dark })
  page.drawText(`$${invoice.balance_due.toFixed(2)}`, { x: 490, y, font: fontBold, size: 11, color: gold })

  // Notes
  if (invoice.notes) {
    y -= 40
    page.drawText('Notes:', { x: 50, y, font: fontBold, size: 9, color: gray }); y -= 12
    page.drawText(invoice.notes.slice(0, 200), { x: 50, y, font, size: 9, color: gray })
  }

  // Footer
  page.drawText('Thank you for your business!', { x: 50, y: 40, font, size: 9, color: gray })
  page.drawText('Generated by Stride', { x: 450, y: 40, font, size: 7, color: rgb(0.7, 0.7, 0.7) })

  const pdfBytes = await pdf.save()

  return new NextResponse(Buffer.from(pdfBytes), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${invoice.invoice_number}.pdf"`,
    },
  })
}
