var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/consent/[ownerId]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__2861e3fd._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_8e084e29._.js")
R.c("server/chunks/ssr/[root-of-the-server]__45111c85._.js")
R.c("server/chunks/ssr/node_modules_722875e3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__4d4728ef._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_consent_[ownerId]_page_actions_30dc557e.js")
R.m(96388)
module.exports=R.m(96388).exports
