var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/calendar/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__8afdfb78._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_4a5b4173._.js")
R.c("server/chunks/ssr/[root-of-the-server]__45111c85._.js")
R.c("server/chunks/ssr/node_modules_722875e3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__4d4728ef._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_calendar_page_actions_aac8256a.js")
R.m(31237)
module.exports=R.m(31237).exports
